version: '2'

services:
  db:
    image: mdillon/postgis
    environment:
      POSTGRES_DB: autumn
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
    ports:
      - 5432
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
  web:
    environment:
      DATABASE_URL: postgres://default:default@db:5432/autumn
    env_file:
      - .docker.env
    build: .
    command: >
      /bin/bash -c "
        python3 manage.py migrate;
        python3 manage.py createsuperuserwithpassword --noinput --username=admin --email=admin@fake.domain --password=pleasechangeme
        python3 manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
