# Generated by Django 3.1 on 2021-09-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210903_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
