# Generated by Django 3.1 on 2021-09-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210907_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepicture',
            name='position',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
