# Generated by Django 3.1 on 2021-09-16 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profilepicture_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilepicture',
            options={'ordering': ['position']},
        ),
    ]
