# Generated by Django 3.1 on 2021-09-17 13:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210916_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'MALE'), (1, 'FEMALE'), (2, 'OTHER')], null=True)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('school', models.CharField(blank=True, default='', max_length=300)),
                ('job', models.CharField(blank=True, default='', max_length=300)),
                ('company', models.CharField(blank=True, default='', max_length=300)),
                ('wants_relationship', models.BooleanField(default=True)),
                ('age_min', models.IntegerField(blank=True, default=18, null=True)),
                ('age_max', models.IntegerField(blank=True, default=50, null=True)),
                ('show_male', models.BooleanField(default=False)),
                ('show_female', models.BooleanField(default=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, geography=True, null=True, srid=4326)),
                ('distance_max', models.IntegerField(blank=True, default=25, null=True)),
                ('show_distance_km', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('allows_notifications', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
