# Generated by Django 3.1 on 2021-09-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210917_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='phone_verification_code',
            field=models.CharField(default=1111, max_length=4),
            preserve_default=False,
        ),
    ]
