# Generated by Django 3.1 on 2021-09-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_signup_phone_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
