# Generated by Django 3.1 on 2021-09-19 01:24

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_signup_is_phone_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
