# Generated by Django 3.1 on 2021-09-19 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210919_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='gender',
        ),
        migrations.AddField(
            model_name='profile',
            name='orientation',
            field=models.IntegerField(blank=True, choices=[(0, 'STRAIGHT'), (1, 'GAY'), (2, 'LESBIAN'), (3, 'BISEXUAL'), (4, 'ASEXUAL'), (5, 'DEMISEXUAL'), (6, 'PANSEXUAL'), (7, 'QUEER'), (8, 'QUESTIONING')], null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='orientation',
            field=models.IntegerField(blank=True, choices=[(0, 'STRAIGHT'), (1, 'GAY'), (2, 'LESBIAN'), (3, 'BISEXUAL'), (4, 'ASEXUAL'), (5, 'DEMISEXUAL'), (6, 'PANSEXUAL'), (7, 'QUEER'), (8, 'QUESTIONING')], null=True),
        ),
        migrations.CreateModel(
            name='ProfileGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='api.gender')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
