# Generated by Django 3.1 on 2021-09-19 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_signupgender'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('position', models.IntegerField(blank=True, default=None, null=True)),
                ('signup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='api.signup')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
