# Generated by Django 3.1 on 2021-09-19 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_signuppicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='importance_interests',
            field=models.IntegerField(blank=True, choices=[(0, 'NONE'), (1, 'LEAST'), (2, 'SOMEWHAT'), (3, 'VERY')], null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='importance_interests',
            field=models.IntegerField(blank=True, choices=[(0, 'NONE'), (1, 'LEAST'), (2, 'SOMEWHAT'), (3, 'VERY')], null=True),
        ),
        migrations.CreateModel(
            name='SignupInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='api.interest')),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='api.signup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
