# Generated by Django 3.1 on 2021-09-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210919_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_verification_code',
            field=models.CharField(default=1111, max_length=4),
            preserve_default=False,
        ),
    ]
