# Generated by Django 3.1 on 2021-09-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_profile_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
