# Generated by Django 3.1 on 2021-09-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_profile_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='like',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
