# Generated by Django 3.1 on 2021-09-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20210921_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
