# Generated by Django 3.1 on 2021-09-28 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='school',
        ),
    ]
