# Generated by Django 3.1 on 2021-10-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_experience_profileexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gradient',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.IntegerField(blank=True, default=None, help_text='Height (inches)', null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='height',
            field=models.IntegerField(blank=True, default=None, help_text='Height (inches)', null=True),
        ),
    ]
