# Generated by Django 3.1 on 2021-11-25 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20211125_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.school'),
        ),
    ]
