# Generated by Django 3.1 on 2021-12-12 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_like_is_ended_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gender'),
        ),
        migrations.AddField(
            model_name='signup',
            name='gender',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gender'),
        ),
    ]
