# Generated by Django 3.1 on 2021-12-12 20:04

from django.db import migrations


def reformat_genders(apps, schema_editor):
    Profile = apps.get_model('api', 'Profile')
    for profile in Profile.objects.all():
        if profile.genders.all().count() > 0:
            profile.gender = profile.genders.all()[0].gender
            profile.save()

    Signup = apps.get_model('api', 'Signup')
    for signup in Signup.objects.all():
        if signup.genders.all().count() > 0:
            signup.gender = signup.genders.all()[0].gender
            signup.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20211212_2003'),
    ]

    operations = [
        migrations.RunPython(reformat_genders),
    ]
