# Generated by Django 3.1 on 2021-12-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20211212_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupgender',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='signupgender',
            name='signup',
        ),
        migrations.DeleteModel(
            name='ProfileGender',
        ),
        migrations.DeleteModel(
            name='SignupGender',
        ),
    ]
