# Generated by Django 3.1 on 2021-12-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20211212_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='is_female_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gender',
            name='is_male_group',
            field=models.BooleanField(default=False),
        ),
    ]
