# Generated by Django 3.1 on 2021-12-12 22:07

from django.db import migrations


def apply_gender_filtering_references(apps, schema_editor):
    Gender = apps.get_model('api', 'Gender')
    for gender in Gender.objects.all():
        g = gender.name.lower()

        if 'ftm' in g:
            gender.is_male_group = True
        elif 'mtf' in g:
            gender.is_female_group = True
        elif 'female to male' in g:
            gender.is_male_group = True
        elif 'male to female' in g:
            gender.is_female_group = True
        elif 'male' in g and 'female' not in g:
            gender.is_male_group = True
        elif 'man' in g and 'woman' not in g:
            gender.is_male_group = True
        elif 'boy' in g:
            gender.is_male_group = True
        elif 'female' in g:
            gender.is_female_group = True
        elif 'woman' in g:
            gender.is_female_group = True

        gender.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20211212_2202'),
    ]

    operations = [
        migrations.RunPython(apply_gender_filtering_references, migrations.RunPython.noop),
    ]
