# Generated by Django 3.1 on 2021-12-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20211212_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='importance_experiences',
            field=models.IntegerField(blank=True, choices=[(0, 'NONE'), (1, 'LEAST'), (2, 'SOMEWHAT'), (3, 'VERY')], null=True),
        ),
    ]
