# Generated by Django 3.1 on 2022-01-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_profile_firebase_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='amity_channel',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
