# Generated by Django 3.1 on 2022-01-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_like_amity_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_tutorial_endconvo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_tutorial_matches',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_tutorial_matchlimit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_tutorial_swiping',
            field=models.BooleanField(default=False),
        ),
    ]
