# Generated by Django 3.1 on 2022-02-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20220126_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deleted_reason_another_offapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='deleted_reason_another_onapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='deleted_reason_bugs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='deleted_reason_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='deleted_reason_quality',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='deleted_reason_quantity',
            field=models.BooleanField(default=False),
        ),
    ]
