# Generated by Django 3.1 on 2022-02-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20220221_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, default=None, max_length=2000, null=True)),
                ('title', models.CharField(default='', max_length=2000)),
                ('body', models.CharField(default='', max_length=2000)),
                ('is_success', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
