# Generated by Django 3.1 on 2022-02-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_notificationlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name']},
        ),
    ]
