# Generated by Django 3.1 on 2022-03-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_autumconfig_region_lock_distance_toronto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autumconfig',
            name='profile_hide_swipedeck_default',
            field=models.BooleanField(help_text='Hide swipedeck before launch?'),
        ),
        migrations.AlterField(
            model_name='autumconfig',
            name='region_lock_distance_toronto',
            field=models.IntegerField(default=42, help_text='Max radius around Toronto for launch'),
        ),
    ]
