# Generated by Django 3.1 on 2022-05-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20220321_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_phone_permission_denied',
            field=models.BooleanField(default=False),
        ),
    ]
