# Generated by Django 3.1 on 2022-05-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_profile_is_phone_permission_denied'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='match_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
