# Generated by Django 3.1 on 2022-05-24 13:23

from django.db import migrations


def count_matches(apps, schema_editor):
    Profile = apps.get_model('api', 'Profile')
    for profile in Profile.objects.all():
        profile.match_count = profile.likes.filter(is_active=True).count() + profile.liked_by.filter(is_active=True).count()
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20220523_1602'),
    ]

    operations = [
        migrations.RunPython(count_matches, migrations.RunPython.noop),
    ]
