# Generated by Django 3.1 on 2022-05-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_auto_20220524_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deleted_reason_other_text',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
    ]
